// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DSPElDialog: typeof import('./components/DSPElDialog/DSPElDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    'IAntDesign:deleteFilled': typeof import('~icons/ant-design/delete-filled')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    IMdiContentDuplicate: typeof import('~icons/mdi/content-duplicate')['default']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IRiArticleLine: typeof import('~icons/ri/article-line')['default']
    'IZondicons:arrowThickDown': typeof import('~icons/zondicons/arrow-thick-down')['default']
    'IZondicons:arrowThickUp': typeof import('~icons/zondicons/arrow-thick-up')['default']
    'IZondicons:indentDecrease': typeof import('~icons/zondicons/indent-decrease')['default']
    'IZondicons:indentIncrease': typeof import('~icons/zondicons/indent-increase')['default']
    Left: typeof import('./components/Left.vue')['default']
    Product: typeof import('./components/product.vue')['default']
    ProductImg: typeof import('./components/ProductImg.vue')['default']
    ProductIMG: typeof import('./components/ProductIMG.vue')['default']
    Right: typeof import('./components/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}
